### ISSUE TITLE
System.Data

### ISSUE THREAD

**Issue by Erhannis** [mguillemot/UnityNpgsql#1]
I have an issue in one project where Visual Studio demands the System.Data library, but won't let me add the reference.  In accordance with instructions from around the internet, I copied "(Unity installation)\Editor\Data\Mono\lib\mono\2.0\System.Data.dll" into my Assets folder, and then things worked.  I'm just opening this issue for people down the road.  (Thanks for the package.)

**Comment by pha3z** [comment]
Because this is a common problem for people who won't know, and Unity is a mess to figure out. I suggest Adding this guy's note about System.Data.dll to the homepage for this project or whatever documentation explains how to use unitynpgsql.dll.
